### ISSUE TITLE
Backend Rearchitecture

### ISSUE THREAD

**Issue by Aboisier** [red-kite-solutions/stalker#58]
# TODO
- [ ] Deserialize jobs properly in Orchestrator
- [ ] Let flowmanager specify the number of retries
- [ ] Kafka auth
- [ ] Cancel job?
- [ ] Make jobs cleaner in Orchestrator (inline python - ew)

#### Idea dump
I believe we should decouple jobs output from the flow manager API so that implementing a new job does not require changing the backend and the front end.

## Job output

All jobs should follow the same output. The output tells the flow manager how the job affects the data.
1. Create a new entity or update an existing one (a host, a port, etc.)
2. Attach "findings" (or "knowledge"?) to an existing entity

Findings are pieces of information related to an entity. A job can output many findings.

 A finding could look something like this.

```js
{
  // Data related to the job
  jobId: "507f1f77bcf86cd799439011",
  job: "SMTP scan"

  // Data linking the finding to an entity
  company: "613e2c54cbf68dd46472838",
  host: "173.246.25.51",
  port: "25",

  // Static data related to the entity
  // ...

  // Custom data that the UI can dynamically render
  customFields: [
    {
      type: "string",
      name: "Service",
      value: "SMTP"
    }
  ]
}
```

## Publishing the result of a job

Jobs should drop the output of their job on the message queue for the flow manager to consume.

## What does it look like?

Dunno

![image](https://user-images.githubusercontent.com/6698529/163474108-9ab48af4-614a-4979-b000-d4affbe88c20.png)
https://excalidraw.com/#room=4980d716742c083310f7,uE2QGhBx5FCwp4s30DQWEg

## Architecture much?

![image](https://user-images.githubusercontent.com/6698529/163589676-a2ea7914-e11b-4dfe-86ec-67609126681e.png)
